language : python
python:
  - 3.4
addons:
  apt_packages:
  - gfortran
  - liblapack-dev
install:
- conda update --yes conda
- conda create -n testenv --yes scipy numpy pip nose setuptools python=3.4
- source activate testenv
# for debugging...
- echo $PATH
- which python
- conda info
- conda list
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p /home/travis/mc
- export PATH=/home/travis/mc/bin:$PATH
before_script:
- pip install coverage
- pip install scipy
- make
- cd tests
script:
- nosetests --with-coverage --with-doctest
