dist: bionic
language : python
compiler:
  - gcc
env:
  - GCC_VERSION=7
addons:
  apt:
    update: true
    packages:
      - gcc
      - g++
      - liblapack-dev
      - libgsl0-dev
      - libeigen3-dev
      - libgmp-dev
      - git
      - libmpfr-dev
      - libboost-all-dev
install:
  - conda update --yes conda
  - conda create -n testenv --yes scipy numpy pip nose setuptools matplotlib
  - source activate testenv
before_install:
  - gcc --version
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  # Build Libint2
  - WORKDIR=$PWD
  - git clone https://github.com/evaleev/libint.git
  - cd libint
  - export CC=gcc
  - export CXX=g++
  - export OPENMPFLAGS=-fopenmp
  - export CXXFLAGS="-std=c++11 -fPIC -Wno-enum-compare $OPENMPFLAGS"
  - export LDFLAGS=$OPENMPFLAGS
  - git checkout master
  - aclocal -I lib/autoconf
  - autoconf
  - ./configure --prefix=$WORKDIR CPPFLAGS='-I/usr/include/eigen3'
  - make -j 4
  - make install
  - cd ..
  # Setting up environment
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:$WORKDIR/include:$WORKDIR/include/libint2:/usr/include/eigen3
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$WORKDIR/include:$WORKDIR/include/libint2:/usr/include/eigen3
  - export LIBRARY_PATH=$LIBRARY_PATH:$WORKDIR/lib
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WORKDIR/lib
before_script:
  - pip install coverage
  - make
script:
  - nosetests --with-coverage --with-doctest
