language : python
python:
  - 3.4
addons:
  apt_packages:
  - gfortran
  - liblapack-dev
before_script:
- pip install coverage
- pip install scipy
- make
script:
- cd tests
- nosetests --with-coverage --with-doctest
