dist: bionic
language : python
compiler:
  - gcc
env:
  - GCC_VERSION=7
addons:
  apt:
    update: true
    packages:
      - gcc
      - g++
      - gfortran
      - liblapack-dev
      - libgsl0-dev
      - libeigen3-dev
      - libgmp-dev
      - git
      - libmpfr-dev
      - libboost-all-dev
before_install:
  - gcc --version
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - conda update --yes conda
  - conda create -n testenv --yes scipy numpy pip nose setuptools matplotlib
  - source activate testenv
  # Build Libint2
  - WORKDIR=$PWD
  # - git clone https://github.com/evaleev/libint.git
  # - cd libint
  # - export CC=gcc
  # - export CXX=g++
  # - export OPENMPFLAGS=-fopenmp
  # - export CXXFLAGS="-std=c++11 -fPIC -Wno-enum-compare $OPENMPFLAGS"
  # - export LDFLAGS=$OPENMPFLAGS
  # - git checkout v2.6.0
  # - ./autogen
  # - mkdir build
  # - cd build
  # - ../configure --prefix=$WORKDIR CPPFLAGS='-I/usr/include/eigen3'
  # - make export -j 4
  # - tar -xzvf libint-2.6.0.tgz
  # - cd libint-2.6.0
  # - cmake -DCMAKE_INSTALL_PREFIX=$WORKDIR -DCMAKE_CXX_COMPILER=g++ CXXFLAGS="-I/usr/include/eigen3" .
  # - cmake --build . -j 4
  # - cmake --build . --target install
  # - cd ../../../
  - wget https://www.dropbox.com/s/195ymylrns04a2a/libint-master-SEP052019.tgz # minimal (default am), G12, fPIC, new
  - tar xzvf libint-master-SEP052019.tgz
  # Build libxc
  - git clone https://gitlab.com/libxc/libxc.git
  - cd libxc
  - git checkout 5.0.0
  - python setup.py install --user
  # - cmake . -Bobjdir -DCMAKE_INSTALL_PREFIX=$WORKDIR
  # - cd objdir
  # - make install -j 4
  # - cd ..
  - cd ..
  # Setting up environment
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:$WORKDIR/include:$WORKDIR/include/libint2:/usr/include/eigen3
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$WORKDIR/include:$WORKDIR/include/libint2:/usr/include/eigen3
  - export LIBRARY_PATH=$LIBRARY_PATH:$WORKDIR/lib
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WORKDIR/lib
install:
  - pip install coverage
  - make -j 4
script:
  - nosetests --with-coverage --with-doctest
